version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: saccos
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: saccos

	saccos:
		build: .
		image: chamaconekt/saccos
		links:
		- postgres
		container_name: saccos
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- saccos
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/saccos-nginx/nginx.conf
		depends_on:
			- saccos
		ports:
			- 80:80
		volumes_from:
			- saccos

volumes:
	saccos-static-files:
		driver:local